services:
  az-demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: az-demo:latest
    environment:
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
